# Generated by Django 5.0.1 on 2024-01-19 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('review_count', models.IntegerField()),
                ('rating_average', models.DecimalField(decimal_places=2, max_digits=3)),
                ('phone_number', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('badge_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('zpid', models.IntegerField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('living_area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date_posted', models.DateTimeField()),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('home_type', models.CharField(max_length=255)),
                ('property_tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_on_zillow', models.IntegerField()),
                ('home_status', models.CharField(max_length=255)),
                ('annual_homeowners_insurance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('rent_zestimate', models.DecimalField(decimal_places=2, max_digits=19)),
                ('brokerage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_view_count', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('students_per_teacher', models.IntegerField()),
                ('size', models.IntegerField()),
                ('level', models.CharField(max_length=255)),
                ('grades', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('price_per_square_foot', models.DecimalField(decimal_places=2, max_digits=19)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
            ],
        ),
        migrations.CreateModel(
            name='NearbyHomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zpid', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('home_type', models.CharField(max_length=255)),
                ('home_status', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.agent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flooring', models.CharField(blank=True, max_length=255, null=True)),
                ('foundation_details', models.CharField(blank=True, max_length=255, null=True)),
                ('accessibility_features', models.CharField(blank=True, max_length=255, null=True)),
                ('garage_spaces', models.IntegerField(blank=True, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('view_type', models.CharField(blank=True, max_length=255, null=True)),
                ('water_view', models.BooleanField(default=False)),
                ('heating', models.CharField(blank=True, max_length=255, null=True)),
                ('cooling', models.CharField(blank=True, max_length=255, null=True)),
                ('construction_materials', models.CharField(blank=True, max_length=255, null=True)),
                ('roof_type', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('hoa_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.property')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.school')),
            ],
        ),
    ]
