# Generated by Django 5.0.1 on 2024-01-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zpid', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('living_area', models.PositiveIntegerField()),
                ('lot_size', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('short_sale', models.BooleanField(default=False)),
                ('year_built', models.PositiveIntegerField()),
                ('heating', models.CharField(max_length=100)),
                ('cooling', models.CharField(blank=True, max_length=100, null=True)),
                ('parking_spaces', models.PositiveIntegerField()),
                ('days_on_zillow', models.PositiveIntegerField()),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_review_date', models.DateTimeField(blank=True, null=True)),
                ('list_date', models.DateField()),
            ],
        ),
    ]
