# Generated by Django 5.0.1 on 2024-01-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_property_time_on_zillow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfeatures',
            name='hoa_fee',
            field=models.CharField(max_length=255),
        ),
    ]
