# Generated by Django 5.0.1 on 2024-01-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_propertyfeatures_hoa_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfeatures',
            name='water_view',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
