# Generated by Django 5.0.1 on 2024-01-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_propertyfeatures_water_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='students_per_teacher',
            field=models.IntegerField(null=True),
        ),
    ]
