# Generated by Django 5.0.1 on 2024-01-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_school_students_per_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='grades',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
