# Generated by Django 5.0.1 on 2024-01-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_school_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfeatures',
            name='lot_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
