# Generated by Django 5.0.1 on 2024-01-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_propertyfeatures_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
