# Generated by Django 5.0.1 on 2024-01-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_pricehistory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price_per_square_foot',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
