# Generated by Django 5.0.1 on 2024-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_pricehistory_price_per_square_foot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='page_view_count',
            field=models.IntegerField(null=True),
        ),
    ]
