# Generated by Django 5.0.1 on 2024-01-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_property_page_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='home_status',
        ),
        migrations.AlterField(
            model_name='agent',
            name='badge_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='review_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nearbyhomes',
            name='home_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nearbyhomes',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='nearbyhomes',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='nearbyhomes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='annual_homeowners_insurance',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='home_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='home_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='living_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_zestimate',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='time_on_zillow',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='propertyfeatures',
            name='water_view',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
