# Generated by Django 5.0.1 on 2024-01-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_nearbyhomes_home_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyhomes',
            name='home_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
