# Generated by Django 5.0.1 on 2024-01-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_nearbyhomes_home_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
