# Generated by Django 5.0.1 on 2024-01-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_rename_image_url_property_imgsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyhomes',
            name='imgSrc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
