# Generated by Django 5.0.1 on 2024-01-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_nearbyhomes_imgsrc_nearbyhomes_street_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='id',
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='annual_homeowners_insurance',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='brokerage_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='date_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='living_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='page_view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='property_tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='rent_zestimate',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='time_on_zillow',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='year_built',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nearbyhomes',
            name='zipcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nearbyhomes',
            name='street_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nearbyhomes',
            name='zpid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
