# Generated by Django 5.0.1 on 2024-01-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_alter_nearbyhomes_street_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='annual_homeowners_insurance',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='brokerage_name',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='date_sold',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='living_area',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='page_view_count',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='property_tax_rate',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='rent_zestimate',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='time_on_zillow',
        ),
        migrations.RemoveField(
            model_name='nearbyhomes',
            name='year_built',
        ),
        migrations.AlterField(
            model_name='nearbyhomes',
            name='country',
            field=models.CharField(default='USA', max_length=255, null=True),
        ),
    ]
