# Generated by Django 5.0.1 on 2024-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_remove_nearbyhomes_annual_homeowners_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyhomes',
            name='living_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nearbyhomes',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
